global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Monitoreo de Prometheus mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # user-service
  - job_name: "user-service"
    static_configs:
      - targets: ["localhost:8080"]
    scrape_interval: 1s
    metrics_path: "/actuator/prometheus"
