global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'microservices-monitor'

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus se monitorea a sí mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Microservicio User Service (corriendo externamente)
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Para servicios externos
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    scrape_timeout: 1s

  

