name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run SonarScanner via Docker
        run: |
          docker run --rm \
          -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v "${{ github.workspace }}:/usr/src" \
          sonarsource/sonar-scanner-cli \
          -Dsonar.organization=alexnt4 \
          -Dsonar.projectKey=alexnt4_monitoring-service-softdev \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io
